export interface CareersInformation{
   critaria?:            string[];
   deliveries?:         string[];
   entryRequirements?:  string[];
   getTitle?:           string;
   goals?:              string[];
   link?:               boolean
   meaning?:            string[];
   mention?:            string;
   mision?:             string[];
   modality?:           string;
   ocupationalMarket?:   string[];
   otherCountries?:     string[];
   professionalProfile?: string[];
   professionalProfileGraduate?: string[];
   relatedCareers?:     string[];
   title:               string;
   imageUrl?:            string;
   purpose?:            string[];
   purposeProfesional?:            string[];
   graduationRequirements?: string[];
   permanenceRequirements?: string[];
   vision?:                 string[];
   legalBases?:            string[];
   academicRegime?:        string[];
   description?:           string[];
   specificAspects?:       string[];
   certification?:         string[]
   type?:                  string;
}